### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by jaredramirez** [eburghar/kakship#1]
Hey there,

Thanks for the great status line!

I'm trying to build this project with Nix, as I use NixOS, but to get that to work I hit an error message:
```
> ERROR: The Cargo.lock file doesn't exist
>
> Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
> when the registry is updated.
```

Would it be possible for you to create & add a Cargo.lock file to this repo?

**Comment by eburghar** [comment]
yes of course. I generated the .gitignore with `gi rust` and forgot to comment the Cargo.lock line. Thanks for reporting
